"use client";
import { FormEvent, useMemo, useState } from "react";
import type { InventoryMovementRecord } from "@/lib/domain";
import type { ProductVariant } from "@/lib/types";

type Row=ProductVariant&{productId:string;product:string};
export function AdminInventoryClient({initialRows,initialMovements,threshold}:{initialRows:Row[];initialMovements:InventoryMovementRecord[];threshold:number}){
 const [rows,setRows]=useState(initialRows); const [movements,setMovements]=useState(initialMovements); const [sku,setSku]=useState(initialRows[0]?.sku||""); const [error,setError]=useState("");
 const low=useMemo(()=>rows.filter(r=>r.stock<=(r.lowStockAt??threshold)).length,[rows,threshold]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);const r=await fetch('/api/admin/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sku,delta:Number(f.get('delta')),reason:f.get('reason'),reference:f.get('reference')})});const d=await r.json().catch(()=>({}));if(!r.ok)return setError(d.error||'Unable to adjust stock.');setRows(cur=>cur.map(row=>row.sku===sku?{...row,stock:d.variant.stock}:row));setMovements(cur=>[d.movement,...cur]);(e.currentTarget.elements.namedItem('delta') as HTMLInputElement).value='';}
 return <><div className="adminPageHeading"><div><p>Stock control</p><h1>Inventory</h1></div><span className="adminMetricChip">{low} low stock</span></div>{error&&<div className="adminAlert">{error}</div>}
 <div className="adminTwoCol inventoryTop"><section className="adminPanel"><div className="adminPanelHeading"><div><h2>Stock adjustment</h2><p>Every change creates an inventory movement.</p></div></div><form className="inventoryAdjustForm" onSubmit={submit}><label>Variant<select value={sku} onChange={e=>setSku(e.target.value)}>{rows.map(r=><option key={r.sku} value={r.sku}>{r.sku} · {r.product} · {r.color}/{r.size}</option>)}</select></label><div className="adminFormGrid"><label>Quantity delta<input name="delta" type="number" required placeholder="+10 or -2"/></label><label>Reference<input name="reference" placeholder="PO-102 / stock count"/></label></div><label>Reason<input name="reason" required placeholder="New shipment, damage, correction..."/></label><button className="adminPrimary">Apply adjustment</button></form></section>
 <section className="adminPanel"><div className="adminPanelHeading"><div><h2>Recent movements</h2><p>Audit trail</p></div></div><div className="movementList">{movements.slice(0,8).map(m=><div key={m.id}><span><strong>{m.sku}</strong><small>{m.reason}{m.reference?` · ${m.reference}`:""}</small></span><b className={m.delta>0?'positive':'negative'}>{m.delta>0?'+':''}{m.delta}</b></div>)}</div></section></div>
 <section className="adminPanel noPad"><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>SKU</th><th>Product</th><th>Color</th><th>Size</th><th>On hand</th><th>State</th></tr></thead><tbody>{rows.map(r=>{const isLow=r.stock<=(r.lowStockAt??threshold);return <tr key={r.sku}><td><strong>{r.sku}</strong></td><td>{r.product}</td><td>{r.color}</td><td>{r.size}</td><td>{r.stock}</td><td><span className={`stockState ${isLow?'low':'ok'}`}>{r.stock===0?'Out of stock':isLow?'Low stock':'Healthy'}</span></td></tr>})}</tbody></table></div></section></>;
}
