"use client";
import { FormEvent, useState } from "react";
import { Plus, Trash2, X } from "lucide-react";
import type { AdminProduct, DiscountRecord } from "@/lib/domain";

function stateOf(d:DiscountRecord){const now=Date.now();if(!d.active)return 'Draft';if(d.startsAt&&new Date(d.startsAt).getTime()>now)return 'Scheduled';if(d.endsAt&&new Date(d.endsAt).getTime()<now)return 'Expired';return 'Active';}
export function AdminDiscountsClient({initialDiscounts,products}:{initialDiscounts:DiscountRecord[];products:AdminProduct[]}){
 const [discounts,setDiscounts]=useState(initialDiscounts);const [open,setOpen]=useState(false);const [error,setError]=useState('');
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const scope=String(f.get('scope')) as DiscountRecord['scope'];const target=String(f.get('target')||'');const r=await fetch('/api/admin/discounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),code:f.get('code')||undefined,type:f.get('type'),value:Number(f.get('value')),scope,targetIds:target?[target]:[],minSubtotal:f.get('minSubtotal')?Number(f.get('minSubtotal')):undefined,startsAt:f.get('startsAt')||undefined,endsAt:f.get('endsAt')||undefined,usageLimit:f.get('usageLimit')?Number(f.get('usageLimit')):undefined,active:true})});const d=await r.json().catch(()=>({}));if(!r.ok)return setError(d.error||'Unable to create discount.');setDiscounts(cur=>[d.discount,...cur]);setOpen(false);}
 async function toggle(d:DiscountRecord){const r=await fetch(`/api/admin/discounts/${d.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:!d.active})});const data=await r.json();if(r.ok)setDiscounts(cur=>cur.map(x=>x.id===d.id?data.discount:x));}
 async function remove(d:DiscountRecord){if(!confirm(`Delete ${d.name}?`))return;const r=await fetch(`/api/admin/discounts/${d.id}`,{method:'DELETE'});if(r.ok)setDiscounts(cur=>cur.filter(x=>x.id!==d.id));}
 return <><div className="adminPageHeading"><div><p>Promotions</p><h1>Discounts</h1></div><button className="adminPrimary" onClick={()=>setOpen(true)}><Plus size={15}/> Create discount</button></div>{error&&<div className="adminAlert">{error}</div>}
 <div className="discountGrid">{discounts.map(d=>{const state=stateOf(d);return <article className={`discountCard ${!d.active?'muted':''}`} key={d.id}><div><span className={`adminStatus ${state==='Active'?'delivered':state==='Scheduled'?'preparing':''}`}>{state}</span><small>{d.code?'Coupon':`${d.scope.toLowerCase()} sale`}</small></div><h2>{d.code||d.name}</h2><p>{d.type==='PERCENTAGE'?`${d.value}%`:`${d.value} EGP`} off · {d.scope.toLowerCase()}</p><footer><span>{d.startsAt?new Date(d.startsAt).toLocaleDateString('en-EG'):'Now'} → {d.endsAt?new Date(d.endsAt).toLocaleDateString('en-EG'):'No end date'}</span><div className="discountActions"><button onClick={()=>toggle(d)}>{d.active?'Pause':'Activate'}</button><button onClick={()=>remove(d)}><Trash2 size={14}/></button></div></footer></article>})}</div>
 {open&&<div className="adminModalBackdrop"><section className="adminModal"><div className="adminModalHead"><div><p>PROMOTION</p><h2>Create discount</h2></div><button onClick={()=>setOpen(false)}><X/></button></div><form className="adminEditorForm" onSubmit={create}><label>Name<input name="name" required placeholder="Weekend drop"/></label><div className="adminFormGrid"><label>Coupon code (optional)<input name="code" placeholder="A2WEEKEND"/></label><label>Scope<select name="scope" defaultValue="ORDER"><option value="ORDER">Whole order</option><option value="PRODUCT">Product</option><option value="COLLECTION">Collection</option></select></label></div><div className="adminFormGrid"><label>Type<select name="type"><option value="PERCENTAGE">Percentage</option><option value="FIXED_AMOUNT">Fixed EGP</option></select></label><label>Value<input name="value" type="number" min="1" required/></label></div><label>Target<select name="target"><option value="">All / not required</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}{Array.from(new Set(products.map(p=>p.collection))).map(c=><option key={c} value={c}>Collection: {c}</option>)}</select></label><div className="adminFormGrid"><label>Minimum spend<input name="minSubtotal" type="number" min="0"/></label><label>Usage limit<input name="usageLimit" type="number" min="1"/></label></div><div className="adminFormGrid"><label>Starts<input name="startsAt" type="datetime-local"/></label><label>Ends<input name="endsAt" type="datetime-local"/></label></div><div className="adminModalActions"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="adminPrimary">Create</button></div></form></section></div>}
 </>;
}
