"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import type { OrderRecord } from "@/lib/domain";
import { formatPrice } from "@/lib/format";

const label=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,m=>m.toUpperCase());
const flow=["NEW","CONFIRMED","PREPARING","SHIPPED","DELIVERED"];
export function OrderLookupClient(){const[orderNumber,setOrderNumber]=useState('');const[phone,setPhone]=useState('');const[order,setOrder]=useState<OrderRecord|null>(null);const[error,setError]=useState('');const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('a2-last-order')||'null');if(saved){setOrderNumber(saved.orderNumber||'');setPhone(saved.phone||'');}}catch{}},[]);
 async function lookup(e?:FormEvent){e?.preventDefault();setBusy(true);setError('');const r=await fetch('/api/orders/lookup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderNumber,phone})});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setOrder(null);return setError(d.error||'Order not found.');}setOrder(d.order);}
 async function requestReturn(){const r=await fetch('/api/orders/return',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderNumber,phone,reason})});const d=await r.json().catch(()=>({}));if(!r.ok)return setError(d.error||'Unable to request return.');setOrder(d.order);setReason('');}
 const idx=order?flow.indexOf(order.status):-1;
 return <div className="orderLookupArea"><form className="orderLookupForm" onSubmit={lookup}><label>Order number<input value={orderNumber} onChange={e=>setOrderNumber(e.target.value.toUpperCase())} placeholder="A2-1049" required/></label><label>Phone number<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="01xxxxxxxxx" required/></label><button className="primaryButton" disabled={busy}>{busy?'Checking…':'Track order'}</button></form>{error&&<div className="checkoutError">{error}</div>}
 {order&&<div className="orderTrackCard detailed"><div><span className="statusDot"/><div><strong>{order.orderNumber}</strong><p>{order.items.reduce((s,i)=>s+i.quantity,0)} items · {formatPrice(order.grandTotal)}</p></div></div><span className={`statusPill ${order.status.toLowerCase()}`}>{label(order.status)}</span>{idx>=0&&<><div className="orderTimeline">{flow.slice(1).map((_,i)=><i key={i} className={i<idx?'done':i===idx?'active':''}/>)}</div><small>New → Confirmed → Preparing → Shipped → Delivered</small></>}<div className="orderLookupItems">{order.items.map(i=><div key={i.id}><span>{i.quantity}× {i.productName}<small>{i.color} / {i.size}</small></span><strong>{formatPrice(i.lineTotal)}</strong></div>)}</div><div className="orderAddress"><span>Delivery to</span><strong>{order.shipping.governorate} · {order.shipping.city}<br/>{order.shipping.street}</strong></div>{order.status==='DELIVERED'&&<div className="returnRequest"><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for return / exchange" rows={2}/><button className="ghostButton" onClick={requestReturn}>Request return / exchange</button></div>}</div>}
 {!order&&<div className="emptyState slim"><h2>Need another piece?</h2><Link className="ghostButton" href="/shop">Continue shopping</Link></div>}</div>}
